#include "prefix/prefix.h"

#include "data-mov/mov.h"
#include "data-mov/movcc.h"
#include "data-mov/movcr.h"
#include "data-mov/xchg.h"
#include "data-mov/push.h"
#include "data-mov/pop.h"
#include "data-mov/leave.h"
#include "data-mov/movzx.h"
#include "data-mov/movsx.h"

#include "arith/dec.h"
#include "arith/inc.h"
#include "arith/neg.h"
#include "arith/imul.h"
#include "arith/mul.h"
#include "arith/idiv.h"
#include "arith/div.h"
#include "arith/sub.h"
#include "arith/add.h"
#include "arith/adc.h"
#include "arith/sbb.h"
#include "arith/bt.h"

#include "logic/and.h"
#include "logic/or.h"
#include "logic/not.h"
#include "logic/xor.h"
#include "logic/sar.h"
#include "logic/shl.h"
#include "logic/shr.h"
#include "logic/shrd.h"
#include "logic/test.h"
#include "logic/cmp.h"
#include "logic/setne.h"
#include "logic/rol.h"

#include "string/rep.h"
#include "string/stos.h"
#include "string/cmps.h"
#include "string/movs.h"

#include "misc/misc.h"

#include "special/special.h"

#include "trans/call.h"
#include "trans/je.h"
#include "trans/jl.h"
#include "trans/jne.h"
#include "trans/jmp.h"
#include "trans/jbe.h"
#include "trans/jle.h"
#include "trans/jg.h"
#include "trans/jge.h"
#include "trans/ret.h"
#include "trans/ja.h"
#include "trans/js.h"
#include "trans/jns.h"
#include "trans/jb.h"
#include "trans/jae.h"

#include "load/lgdt.h"
#include "load/mov_s.h"
#include "load/out.h"
#include "load/xchg.h"
